GET http://localhost:3000/events


###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "New Event",
  "description": "This is a event",
  "date": "2024-06-20T18:00:00",
  "price": 100
}

###
@eventId = {{ createEvent.response.body.id }}


###
GET http://localhost:3000/events/{{ eventId }}


###
PATCH http://localhost:3000/events/{{ eventId }}
Content-Type: application/json

{
  "name": "New Event",
  "description": "This is THE event",
  "date": "2024-06-20T18:00:00",
  "price": 100
}


###
DELETE http://localhost:3000/events/{{ eventId }}
